services:
  django_gunicorn:
    volumes:
      - static:/app/staticfiles
      - media:/app/media
      - ./db.sqlite3:/app/db.sqlite3
    env_file:
      - .env
    build:
      context: .
    expose:
      - 8000
  nginx:
    build: ./nginx
    volumes:
      - static:/app/staticfiles
      - media:/app/media
      - ./db.sqlite3:/app/db.sqlite3
    ports:
      - "8000:80"
    depends_on:
      - django_gunicorn

volumes:
  static:
  media:
