# Generated by Django 4.2 on 2023-05-02 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sdcc_compiler', '0002_directory_parent_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='directory',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
