# Generated by Django 4.2 on 2023-05-03 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sdcc_compiler', '0006_remove_file_path_file_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='directory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='files', to='sdcc_compiler.directory'),
        ),
    ]
