# Generated by Django 4.2 on 2023-05-04 09:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sdcc_compiler', '0009_file_access_change_file_creation_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='directory',
            name='access_change',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='directory',
            name='creation_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='directory',
            name='last_modification',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
